# Generated by Django 3.2.7 on 2021-09-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heading',
            new_name='Topic',
        ),
    ]
