# Generated by Django 3.2.7 on 2021-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210901_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='post_images'),
        ),
    ]
