# Generated by Django 3.2.7 on 2021-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='post_images/'),
        ),
    ]
