# Generated by Django 3.2.7 on 2021-09-01 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
