# Generated by Django 3.2.7 on 2021-09-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_content_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(default=2, max_length=1024),
            preserve_default=False,
        ),
    ]
